import React from 'react';

interface PrivacyPolicyModalProps {
  content: 'privacy' | 'terms';
  onClose: () => void;
}

const PrivacyPolicyContent: React.FC = () => (
  <>
    <h3 className="text-xl font-bold mb-4">Privacy Policy</h3>
    <p className="mb-2">Last updated: {new Date().toLocaleDateString()}</p>
    <p className="mb-4">This Privacy Policy describes how OmniClock AI handles your information.</p>

    <h4 className="text-lg font-semibold mb-2">Information We Collect</h4>
    <p className="mb-4">OmniClock AI is designed with your privacy in mind. We do not collect any personally identifiable information. All settings, including alarms, saved world clocks, and theme preferences, are stored locally on your device using your browser's localStorage. This data is never transmitted to our servers.</p>

    <h4 className="text-lg font-semibold mb-2">AI Assistant and Gemini API</h4>
    <p className="mb-4">When you use the AI Assistant feature, your text queries are sent to Google's Gemini API to generate a response. We do not log or store these queries. Your interaction with the Gemini API is subject to Google's Privacy Policy, which you can review here: <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-[var(--accent)] hover:underline">https://policies.google.com/privacy</a>.</p>

    <h4 className="text-lg font-semibold mb-2">Third-Party Services</h4>
    <p className="mb-4">We do not use any third-party analytics or advertising services that track your behavior across websites.</p>
  </>
);

const TermsOfServiceContent: React.FC = () => (
  <>
    <h3 className="text-xl font-bold mb-4">Terms of Service</h3>
    <p className="mb-2">Last updated: {new Date().toLocaleDateString()}</p>
    
    <h4 className="text-lg font-semibold mb-2">1. Acceptance of Terms</h4>
    <p className="mb-4">By accessing or using OmniClock AI, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the service.</p>

    <h4 className="text-lg font-semibold mb-2">2. Use of the Service</h4>
    <p className="mb-4">OmniClock AI is provided for your personal, non-commercial use. You are responsible for any content you input into the AI Assistant feature. You agree not to use the service for any illegal or unauthorized purpose.</p>
    
    <h4 className="text-lg font-semibold mb-2">3. AI Assistant Disclaimer</h4>
    <p className="mb-4">The responses provided by the AI Assistant are generated by an AI model and are for informational purposes only. While we strive for accuracy, we do not guarantee the completeness or correctness of the information provided. Do not rely on the AI for critical advice.</p>
    
    <h4 className="text-lg font-semibold mb-2">4. Disclaimer of Warranties</h4>
    <p className="mb-4">The service is provided on an "AS IS" and "AS AVAILABLE" basis. We disclaim all warranties of any kind, whether express or implied.</p>

    <h4 className="text-lg font-semibold mb-2">5. Limitation of Liability</h4>
    <p className="mb-4">In no event shall OmniClock AI or its developers be liable for any indirect, incidental, special, consequential or punitive damages arising out of or in connection with your use of the service.</p>
  </>
);


export const PrivacyPolicyModal: React.FC<PrivacyPolicyModalProps> = ({ content, onClose }) => {
  const title = content === 'privacy' ? 'Privacy Policy' : 'Terms of Service';

  return (
    <div className="fixed inset-0 bg-[var(--background)]/70 backdrop-blur-sm flex items-center justify-center z-50 animate-fadeIn" onClick={onClose}>
      <div className="w-full max-w-2xl h-[80vh] neumorphic-flat flex flex-col mx-4" onClick={e => e.stopPropagation()}>
        <header className="flex items-center justify-between p-4 border-b border-[var(--shadow-dark)] flex-shrink-0">
          <h2 className="text-xl font-bold text-[var(--accent)]">{title}</h2>
          <button onClick={onClose} className="text-[var(--text-secondary)] hover:text-[var(--text-primary)] text-3xl font-light">
             &times;
          </button>
        </header>

        <main className="flex-grow p-6 overflow-y-auto custom-scrollbar text-[var(--text-secondary)] space-y-4 leading-relaxed">
          {content === 'privacy' ? <PrivacyPolicyContent /> : <TermsOfServiceContent />}
        </main>
      </div>
    </div>
  );
};